apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:dee7eb77aec561e2e16d4b327df3f25d4aff2de4510469d57b342044902ca729
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:041825e7fd887b105d02ec9361aa4a5ab416326667b5eb8e98a2ed443f278cb5
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:4c17161781f70339cc38c35e8635b97184e4779f1d0c243a477d3ee293d85730
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder@sha256:fdde4691708e2eaebbc7fb8ed7be4eaf6d7cedae9fca3a5ca23ddf95af710f96
    - name: tekton-bundle-builder-oci-ta
      bundle: quay.io/konflux-ci/pull-request-builds:tekton-bundle-builder-oci-ta-7bd35399f1635e2ec97671e1a8d96a425c4a2825@sha256:cfd4f8d488b89d1d5c99143bf518661e5e2311f37ad92ee3cb83c1c2ef4900f3
