apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:c948d1555ec98213fe3bf5e07f01575f5af1f9ddf99e1487afa6d6b852a1d3a2
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:705903cbc5019e27f774e723a0b49edd0d3d7257d0c99415e46ff718609402e9
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:69d7bc0ed293ca0a11cfdb75c243eaddeb98871dde111fe62645d6b66a1be593
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder@sha256:867fe4416a07ab1c7317a7698d8323fb3f01133d8d4559b786c6f7a7d54604b6
    - name: tekton-bundle-builder-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder-oci-ta@sha256:3af7b09db0949b403bb67db4995439afb743322d620f5432ba4b5e08d1ec9069
