kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - proxy.yaml
  - rbac.yaml

images:
- name: quay.io/avi_test/avi-ui
  newName: quay.io/avi_test/avi-ui
  newTag: latest

configMapGenerator:
  - name: proxy
    files:
      - nginx.conf
  - name: proxy-init-config
    literals:
      - IMPERSONATE=true
      - TEKTON_RESULTS_URL=https://tekton-results-api-service.tekton-pipelines.svc.cluster.local:8080

namespace: konflux-ui
