---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - smee-client.yaml

images:
  - name: ghcr.io/chmouel/gosmee
    newName: ghcr.io/chmouel/gosmee
    newTag: v0.26.1
  - name: quay.io/konflux-ci/smee-sidecar
    newName: quay.io/konflux-ci/smee-sidecar
    newTag: latest@sha256:eed09ba0225c94e210e5a16f5af8a157f4991b50518412b4c9f7c4876f226630

patches:
  - path: smee-channel-id.yaml
    target:
      kind: Deployment
      name: gosmee-client
